# Generated by Django 3.1.5 on 2021-08-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0003_auto_20210818_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galaxy',
            options={'verbose_name_plural': 'Galaxies'},
        ),
    ]
