# Generated by Django 3.1.5 on 2021-08-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0009_auto_20210818_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalframe',
            name='player',
            field=models.ForeignKey(null=0, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='bowling.player'),
        ),
    ]
