# Generated by Django 3.1.5 on 2021-08-22 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0010_auto_20210822_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalframe',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='bowling.player'),
        ),
    ]
